import { db } from "@workspace/db";
import { goalLibraryTable } from "@workspace/db/schema";

const goals = [
  // ─── Module: Emotional Regulation ───────────────────────────────────────
  {
    goalId: "ER-001",
    module: "Emotional Regulation",
    ageRangeMin: 6, ageRangeMax: 12,
    area: "Emotional",
    subarea: "Affect Identification",
    goalName: "Identify and label basic emotions",
    clinicalDescription: "The patient will develop the ability to identify and correctly label primary emotions (happiness, sadness, anger, fear, disgust, surprise) in self and others using visual and verbal cues.",
    successIndicator: "Patient correctly identifies at least 5 of 6 primary emotions in 4 out of 5 opportunities across 3 consecutive sessions.",
    suggestedActivities: "Emotion faces matching cards; body scan check-ins; feeling thermometer worksheets; facial expression mirror exercises; emotion journals.",
  },
  {
    goalId: "ER-002",
    module: "Emotional Regulation",
    ageRangeMin: 8, ageRangeMax: 18,
    area: "Emotional",
    subarea: "Affect Regulation",
    goalName: "Apply self-regulation strategies during distress",
    clinicalDescription: "The patient will learn and apply at least three evidence-based self-regulation strategies (e.g., diaphragmatic breathing, progressive muscle relaxation, grounding techniques) when experiencing emotional distress.",
    successIndicator: "Patient independently uses a regulation strategy to reduce subjective distress (measured by SUD scale) by at least 30% in 3 of 4 triggered situations.",
    suggestedActivities: "4-7-8 breathing practice; body scan guided audio; cold water grounding; 5-4-3-2-1 sensory technique; stress ball exercises.",
  },
  {
    goalId: "ER-003",
    module: "Emotional Regulation",
    ageRangeMin: 13, ageRangeMax: 99,
    area: "Emotional",
    subarea: "Emotional Awareness",
    goalName: "Increase emotional vocabulary and nuance",
    clinicalDescription: "The patient will expand their emotional vocabulary beyond basic categories to include nuanced emotional states, increasing self-awareness and precision in emotional communication.",
    successIndicator: "Patient spontaneously uses 10+ distinct emotion words in session and can distinguish between similar emotions (e.g., frustrated vs. angry) in 80% of opportunities.",
    suggestedActivities: "Feelings wheel exploration; emotion journaling with nuanced descriptors; narrative therapy techniques; literary character emotion analysis.",
  },
  {
    goalId: "ER-004",
    module: "Emotional Regulation",
    ageRangeMin: 6, ageRangeMax: 99,
    area: "Emotional",
    subarea: "Distress Tolerance",
    goalName: "Tolerate emotional discomfort without avoidance",
    clinicalDescription: "The patient will develop the capacity to experience and tolerate negative emotions without resorting to avoidance, suppression, or maladaptive coping behaviors.",
    successIndicator: "Patient remains engaged during emotionally difficult content for 15+ minutes without avoidance behaviors in 4 consecutive sessions.",
    suggestedActivities: "TIPP skills (Temperature, Intense exercise, Paced breathing, Paired muscle relaxation); distress tolerance hierarchy exercises; mindfulness sitting with discomfort.",
  },
  // ─── Module: Cognitive Restructuring ────────────────────────────────────
  {
    goalId: "CR-001",
    module: "Cognitive Restructuring",
    ageRangeMin: 10, ageRangeMax: 99,
    area: "Cognitive",
    subarea: "Thought Identification",
    goalName: "Identify automatic negative thoughts",
    clinicalDescription: "The patient will learn to recognize and record automatic negative thoughts (ANTs) triggered by specific situations, developing metacognitive awareness as a foundation for cognitive restructuring.",
    successIndicator: "Patient independently completes a thought record identifying the situation, automatic thought, and emotional response in 80% of assigned homework across 4 weeks.",
    suggestedActivities: "ABC thought logs; thought catching worksheets; Socratic questioning in session; cognitive diary mobile app; thought bubble drawing exercises.",
  },
  {
    goalId: "CR-002",
    module: "Cognitive Restructuring",
    ageRangeMin: 12, ageRangeMax: 99,
    area: "Cognitive",
    subarea: "Cognitive Distortions",
    goalName: "Identify and challenge cognitive distortions",
    clinicalDescription: "The patient will identify common cognitive distortions (all-or-nothing thinking, catastrophizing, mind reading, fortune telling, personalization) in their thought patterns and challenge them using evidence-based techniques.",
    successIndicator: "Patient correctly identifies distortion type and generates a balanced alternative thought in 75% of thought records over 3 consecutive sessions.",
    suggestedActivities: "Cognitive distortions checklist; evidence for/against worksheets; behavioral experiments; pie charts for responsibility; double-standard technique.",
  },
  {
    goalId: "CR-003",
    module: "Cognitive Restructuring",
    ageRangeMin: 14, ageRangeMax: 99,
    area: "Cognitive",
    subarea: "Core Beliefs",
    goalName: "Identify and modify maladaptive core beliefs",
    clinicalDescription: "The patient will identify underlying core beliefs and schemas driving dysfunctional patterns and develop more adaptive, balanced belief alternatives through schema therapy and behavioral experiments.",
    successIndicator: "Patient identifies at least 2 core maladaptive beliefs and their origin, rates conviction in adaptive alternative belief at 60%+ on 3 consecutive assessments.",
    suggestedActivities: "Schema identification worksheets; historical evidence review; positive data log; compassionate mind training; imagery rescripting.",
  },
  // ─── Module: Behavioral Activation ──────────────────────────────────────
  {
    goalId: "BA-001",
    module: "Behavioral Activation",
    ageRangeMin: 10, ageRangeMax: 99,
    area: "Behavioral",
    subarea: "Activity Scheduling",
    goalName: "Increase engagement in pleasurable activities",
    clinicalDescription: "The patient will systematically increase engagement in valued and pleasurable activities to counteract behavioral withdrawal and depression-maintaining avoidance patterns.",
    successIndicator: "Patient completes at least 5 scheduled pleasurable activities per week and reports average mood improvement of 2+ points on a 10-point scale compared to baseline.",
    suggestedActivities: "Activity pleasurability/mastery rating; weekly activity scheduling; behavioral activation hierarchy; mood monitoring charts; reward system planning.",
  },
  {
    goalId: "BA-002",
    module: "Behavioral Activation",
    ageRangeMin: 12, ageRangeMax: 99,
    area: "Behavioral",
    subarea: "Avoidance Reduction",
    goalName: "Reduce avoidance behaviors through graded exposure",
    clinicalDescription: "The patient will construct and systematically work through an avoidance hierarchy, gradually confronting avoided situations to break the avoidance-anxiety cycle.",
    successIndicator: "Patient advances through 70% of their individualized avoidance hierarchy with SUDs decreasing by 50%+ from initial exposure across 8 weeks.",
    suggestedActivities: "Fear hierarchy construction; SUDS rating tracking; imaginal and in-vivo exposure; interoceptive exposure exercises; behavioral experiment recording.",
  },
  {
    goalId: "BA-003",
    module: "Behavioral Activation",
    ageRangeMin: 8, ageRangeMax: 99,
    area: "Behavioral",
    subarea: "Routine Building",
    goalName: "Establish and maintain consistent daily routine",
    clinicalDescription: "The patient will develop and sustain a structured daily routine incorporating sleep hygiene, physical activity, nutritional regularity, and productive time blocks to support mood stability.",
    successIndicator: "Patient adheres to established daily routine with 75%+ consistency for 4 consecutive weeks as measured by self-monitoring charts.",
    suggestedActivities: "Sleep diary monitoring; routine mapping worksheet; habit stacking techniques; visual schedule boards; digital routine tracking app.",
  },
  // ─── Module: Social Skills ───────────────────────────────────────────────
  {
    goalId: "SS-001",
    module: "Social Skills",
    ageRangeMin: 6, ageRangeMax: 18,
    area: "Social",
    subarea: "Peer Interaction",
    goalName: "Initiate and maintain peer conversations",
    clinicalDescription: "The patient will develop skills to independently initiate, sustain, and appropriately conclude conversations with peers, including topic selection, turn-taking, and responding to social cues.",
    successIndicator: "Patient successfully initiates conversation with a peer, maintains exchange for 3+ turns, and closes appropriately in 4 of 5 structured social opportunities.",
    suggestedActivities: "Conversation scripts and role-play; social autopsies; video modeling; lunch buddy programs; structured peer dyads; conversation game activities.",
  },
  {
    goalId: "SS-002",
    module: "Social Skills",
    ageRangeMin: 8, ageRangeMax: 99,
    area: "Social",
    subarea: "Assertiveness",
    goalName: "Express needs and boundaries assertively",
    clinicalDescription: "The patient will differentiate between passive, aggressive, and assertive communication styles and apply assertive communication techniques to express needs, preferences, and boundaries effectively.",
    successIndicator: "Patient demonstrates assertive communication (verbal and non-verbal) in 3 role-play scenarios and reports using assertiveness in at least 2 real-life situations per week.",
    suggestedActivities: "Assertiveness style identification; I-statement practice; DESC scripting; video feedback on body language; real-life scenario rehearsal; refusal skill practice.",
  },
  {
    goalId: "SS-003",
    module: "Social Skills",
    ageRangeMin: 10, ageRangeMax: 99,
    area: "Social",
    subarea: "Empathy & Perspective-Taking",
    goalName: "Demonstrate empathy and perspective-taking",
    clinicalDescription: "The patient will develop the ability to consider situations from another person's perspective, recognize others' emotional states, and respond with appropriate empathic responses.",
    successIndicator: "Patient accurately identifies another person's perspective and provides an empathic verbal response in 80% of role-play opportunities across 3 sessions.",
    suggestedActivities: "Perspective-taking comic strips; character emotion journals; movie scene analysis; empathy mapping; community helping projects.",
  },
  // ─── Module: Trauma Processing ───────────────────────────────────────────
  {
    goalId: "TR-001",
    module: "Trauma Processing",
    ageRangeMin: 8, ageRangeMax: 99,
    area: "Emotional",
    subarea: "Trauma Psychoeducation",
    goalName: "Understand trauma's impact on the body and mind",
    clinicalDescription: "The patient will develop an understanding of the neurobiological and psychological effects of trauma, including the stress response system, window of tolerance, and trauma-related symptoms.",
    successIndicator: "Patient can verbally explain at least 3 ways trauma affects the body/mind and identifies 2 personal trauma responses in their own experience.",
    suggestedActivities: "Window of tolerance diagram; stress response psychoeducation handouts; trauma body mapping; brain anatomy psychoeducation (hand model); polyvagal theory basics.",
  },
  {
    goalId: "TR-002",
    module: "Trauma Processing",
    ageRangeMin: 12, ageRangeMax: 99,
    area: "Emotional",
    subarea: "Trauma Narrative",
    goalName: "Develop integrated trauma narrative",
    clinicalDescription: "The patient will process traumatic memories through the construction of a coherent, integrated trauma narrative that contextualizes events and reduces the fragmented, overwhelming quality of trauma memories.",
    successIndicator: "Patient constructs a written or verbal trauma narrative, rates trauma memory distress (SUD) at 3 or below, and reports narrative no longer feels overwhelming across 2 consecutive sessions.",
    suggestedActivities: "Trauma narrative writing; TF-CBT narrative activities; EMDR processing; timeline construction; narrative exposure therapy exercises.",
  },
  // ─── Module: Executive Function ──────────────────────────────────────────
  {
    goalId: "EF-001",
    module: "Executive Function",
    ageRangeMin: 7, ageRangeMax: 18,
    area: "Cognitive",
    subarea: "Planning & Organization",
    goalName: "Improve planning and task organization skills",
    clinicalDescription: "The patient will develop age-appropriate planning and organizational strategies to independently break multi-step tasks into manageable components and sequence them effectively.",
    successIndicator: "Patient independently creates a step-by-step plan for assigned tasks with 80% accuracy and completes multi-step tasks on time in 4 of 5 opportunities.",
    suggestedActivities: "Task analysis worksheets; project planning templates; visual checklists; time estimation practice; digital planner setup; backward chaining exercises.",
  },
  {
    goalId: "EF-002",
    module: "Executive Function",
    ageRangeMin: 7, ageRangeMax: 99,
    area: "Cognitive",
    subarea: "Attention & Focus",
    goalName: "Sustain attention on tasks for increasing durations",
    clinicalDescription: "The patient will develop strategies to sustain focused attention on tasks for progressively longer periods, reducing off-task behavior and improving task completion rates.",
    successIndicator: "Patient maintains on-task behavior for 20+ continuous minutes in 4 of 5 sessions and reports using at least 2 attention strategies independently.",
    suggestedActivities: "Pomodoro technique training; mindfulness attention exercises; sensory break schedules; external cueing systems; fidget tool trials; focus music protocols.",
  },
  {
    goalId: "EF-003",
    module: "Executive Function",
    ageRangeMin: 8, ageRangeMax: 99,
    area: "Cognitive",
    subarea: "Impulse Control",
    goalName: "Reduce impulsive responses through self-monitoring",
    clinicalDescription: "The patient will learn and apply cognitive strategies to recognize impulsive urges and pause before responding, improving self-regulation in academic, social, and daily life contexts.",
    successIndicator: "Patient demonstrates a pause-and-consider strategy (STOP technique or equivalent) before responding in 70% of identified high-risk situations over 4 weeks.",
    suggestedActivities: "STOP-THINK-ACT protocol; traffic light system; self-talk scripting; consequence mapping; impulse journal; role-play with wait-time practice.",
  },
  // ─── Module: Anxiety Management ─────────────────────────────────────────
  {
    goalId: "AN-001",
    module: "Anxiety Management",
    ageRangeMin: 6, ageRangeMax: 99,
    area: "Behavioral",
    subarea: "Exposure & Response Prevention",
    goalName: "Complete exposure hierarchy for primary fear",
    clinicalDescription: "The patient will systematically work through a personalized exposure hierarchy for their primary fear domain, habituating to feared stimuli and extinguishing avoidance responses.",
    successIndicator: "Patient completes all hierarchy steps with final SUD rating of 3 or less and demonstrates willingness to approach previously avoided stimuli independently.",
    suggestedActivities: "Hierarchical in-vivo exposure; imaginal exposure sessions; interoceptive exposure; response prevention practice; exposure homework recordings.",
  },
  {
    goalId: "AN-002",
    module: "Anxiety Management",
    ageRangeMin: 8, ageRangeMax: 99,
    area: "Cognitive",
    subarea: "Worry Management",
    goalName: "Reduce excessive worry through structured techniques",
    clinicalDescription: "The patient will apply worry management techniques to contain and evaluate worry thoughts, reducing the frequency and intensity of worry episodes and their interference with daily functioning.",
    successIndicator: "Patient reports worry frequency reduced by 50% from baseline on worry diary, and worry interference score decreases by 30%+ on validated measure.",
    suggestedActivities: "Scheduled worry time; worry postponement; worry decision tree; constructive worry vs. hypothetical worry distinction; mindfulness-based worry defusion.",
  },
  // ─── Module: Sleep & Lifestyle ───────────────────────────────────────────
  {
    goalId: "SL-001",
    module: "Sleep & Lifestyle",
    ageRangeMin: 10, ageRangeMax: 99,
    area: "Physical",
    subarea: "Sleep Hygiene",
    goalName: "Establish consistent sleep hygiene routine",
    clinicalDescription: "The patient will identify and modify sleep-disruptive behaviors, implementing evidence-based sleep hygiene practices to achieve consistent, restorative sleep and reduce insomnia symptoms.",
    successIndicator: "Patient reports consistent bedtime within 30-minute window, sleep onset within 20 minutes, and 7+ hours of sleep on 5+ nights per week for 4 consecutive weeks.",
    suggestedActivities: "Sleep diary monitoring; stimulus control instructions; sleep restriction planning; bedtime routine design; screen time management; relaxation pre-sleep ritual.",
  },
  {
    goalId: "SL-002",
    module: "Sleep & Lifestyle",
    ageRangeMin: 8, ageRangeMax: 99,
    area: "Physical",
    subarea: "Physical Activity",
    goalName: "Increase physical activity to support mental health",
    clinicalDescription: "The patient will progressively increase engagement in regular physical activity to leverage exercise's evidence-based benefits for mood regulation, anxiety reduction, and cognitive function.",
    successIndicator: "Patient engages in 150+ minutes of moderate physical activity per week for 6 consecutive weeks and reports improved mood on exercise days.",
    suggestedActivities: "Activity preference exploration; exercise scheduling; step count monitoring; nature walk therapy; movement breaks during study; yoga or tai chi introduction.",
  },
  // ─── Module: Mindfulness & Acceptance ───────────────────────────────────
  {
    goalId: "MA-001",
    module: "Mindfulness & Acceptance",
    ageRangeMin: 10, ageRangeMax: 99,
    area: "Cognitive",
    subarea: "Present-Moment Awareness",
    goalName: "Develop consistent mindfulness meditation practice",
    clinicalDescription: "The patient will establish a regular mindfulness practice, developing the capacity for present-moment, non-judgmental awareness of thoughts, emotions, and sensory experiences.",
    successIndicator: "Patient completes 10+ minutes of mindfulness practice on 5+ days per week for 6 consecutive weeks and reports increased non-reactive awareness in daily life.",
    suggestedActivities: "Body scan meditation; breath awareness practice; RAIN technique; mindful eating exercises; 3-minute breathing space; open monitoring meditation.",
  },
  {
    goalId: "MA-002",
    module: "Mindfulness & Acceptance",
    ageRangeMin: 14, ageRangeMax: 99,
    area: "Behavioral",
    subarea: "Values Clarification",
    goalName: "Identify and act in alignment with personal values",
    clinicalDescription: "The patient will clarify their core values across life domains and increase engagement in values-consistent behavior as a foundation for meaningful action and psychological flexibility.",
    successIndicator: "Patient identifies top 5 personal values, creates a values-based action plan, and reports completing at least 3 values-consistent activities per week for 4 weeks.",
    suggestedActivities: "Values card sort; values bull's-eye worksheet; committed action planning; values journaling; obituary letter exercise; Bull's Eye diary.",
  },
];

async function seedGoalLibrary() {
  console.log("Seeding goal library...");
  await db.delete(goalLibraryTable);
  const inserted = await db.insert(goalLibraryTable).values(goals).returning();
  console.log(`Seeded ${inserted.length} library goals`);
}

seedGoalLibrary().catch(console.error).finally(() => process.exit(0));
