import { db } from "@workspace/db";
import { goalLibraryTable } from "@workspace/db/schema";

const goals = [
  // ─── LENGUAJE ────────────────────────────────────────────────────────────────
  {
    idObjetivo: "NL-001",
    modulo: "Neurolengua",
    area: "Lenguaje Expresivo",
    areaClinica: "lenguaje",
    subarea: "Léxico",
    franjaEtaria: "2-4",
    nivelDificultad: "básico",
    nombreObjetivo: "Ampliar el vocabulario expresivo en contexto funcional",
    definicionOperativa: "El/la paciente incrementará su léxico expresivo nominando correctamente objetos, personas y acciones de su entorno cotidiano, en situaciones espontáneas y estructuradas.",
    actividadesClinicas: "Juegos de denominación con tarjetas temáticas. Rutinas de nombrar objetos del entorno clínico. Juego simbólico con vocabulario dirigido. Láminas de categorías semánticas.",
    actividadesFamilia: "Nombrar objetos del hogar durante las comidas. Nombrar ropa al vestirse. Leer cuentos con imágenes señalando y nombrando. Juego del 'qué es esto' durante el baño.",
    metaPorcentaje: "80% en 4 de 5 oportunidades",
    intentosSugeridos: "10 por sesión",
    recomendacionClinica: "Contextualizar el vocabulario en rutinas del hogar. Evitar correcciones directas; modelar la forma correcta.",
    indicadorTipo: "Denominación espontánea",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-002",
    modulo: "Neurolengua",
    area: "Lenguaje Expresivo",
    areaClinica: "lenguaje",
    subarea: "Morfosintaxis",
    franjaEtaria: "2-4",
    nivelDificultad: "básico",
    nombreObjetivo: "Producir oraciones simples de estructura sujeto-verbo-objeto",
    definicionOperativa: "El/la paciente producirá oraciones simples de 3 o más palabras con estructura SVO en respuesta a preguntas y en situaciones de narración espontánea.",
    actividadesClinicas: "Modelado de oraciones durante el juego. Expansiones lingüísticas. Narración de láminas de acción. Completar frases con apoyo visual.",
    actividadesFamilia: "Preguntar '¿qué está haciendo?' al mirar cuentos. Expandir las frases del niño añadiendo sujeto o complemento. Describir lo que hacen juntos durante actividades diarias.",
    metaPorcentaje: "75% de oportunidades en 3 sesiones consecutivas",
    intentosSugeridos: "8 por sesión",
    recomendacionClinica: "Usar expansiones y recasts. No exigir repetición; modelar de forma natural en el juego.",
    indicadorTipo: "Muestra de lenguaje espontáneo",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-003",
    modulo: "Neurolengua",
    area: "Lenguaje Comprensivo-Expresivo",
    areaClinica: "lenguaje",
    subarea: "Comprensión",
    franjaEtaria: "4-7",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Comprender y ejecutar instrucciones de dos o más pasos",
    definicionOperativa: "El/la paciente comprenderá instrucciones verbales que incluyan 2 o más acciones secuenciadas, sin apoyo gestual del examinador.",
    actividadesClinicas: "Instrucciones durante actividades de juego. Seguimiento de consignas en tareas de papel. Juegos de roles con instrucciones encadenadas. Actividades de cocina o construcción.",
    actividadesFamilia: "Dar instrucciones cotidianas en dos pasos ('agarra tu mochila y ponla en la silla'). Juego de 'Simón dice' con dos acciones. Rutinas con pasos explícitos.",
    metaPorcentaje: "80% en 4 de 5 oportunidades",
    intentosSugeridos: "6 por sesión",
    recomendacionClinica: "Verificar que no haya dificultades auditivas. Comenzar con instrucciones de contenido familiar.",
    indicadorTipo: "Ejecución conductual",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-004",
    modulo: "Neurolengua",
    area: "Lenguaje Narrativo",
    areaClinica: "lenguaje",
    subarea: "Narrativo",
    franjaEtaria: "4-8",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Narrar eventos con estructura temporal coherente",
    definicionOperativa: "El/la paciente narrará eventos pasados o cuentos con al menos 5 proposiciones ordenadas temporalmente, incluyendo inicio, desarrollo y cierre.",
    actividadesClinicas: "Renarración de cuentos con apoyo de secuencias de imágenes. Narración de eventos propios. Uso de organizadores visuales de historia. Grabación y escucha de sus narraciones.",
    actividadesFamilia: "Pedir al niño que cuente cómo fue su día escolar. Leer y luego preguntar '¿qué pasó primero, después y al final?'. Armar álbumes de fotos narrando lo ocurrido.",
    metaPorcentaje: "Narración con 5+ proposiciones coherentes en 3 de 4 muestras",
    intentosSugeridos: "2-3 narrativas por sesión",
    recomendacionClinica: "Usar preguntas facilitadoras, no interrumpir. Registrar longitud y coherencia del relato.",
    indicadorTipo: "Análisis narrativo",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-005",
    modulo: "Neurolengua",
    area: "Lenguaje Expresivo",
    areaClinica: "lenguaje",
    subarea: "Conectores",
    franjaEtaria: "6-10",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Usar conectores causales y temporales en discurso oral",
    definicionOperativa: "El/la paciente usará de forma apropiada conectores causales (porque, ya que, por eso) y temporales (primero, después, finalmente) en su producción oral espontánea y estructurada.",
    actividadesClinicas: "Completar oraciones con conectores. Explicar causas de eventos. Narrar con apoyo de conectores escritos en tarjetas. Análisis de cuentos señalando conectores.",
    actividadesFamilia: "Preguntar '¿por qué crees que pasó eso?' al leer cuentos. Armar secuencias de acciones con palabras de orden (primero, luego, por último).",
    metaPorcentaje: "80% de uso correcto en muestra de discurso",
    intentosSugeridos: "5 por sesión",
    recomendacionClinica: "Trabajar primero temporales, luego causales. Usar actividades de causalidad física antes de social.",
    indicadorTipo: "Análisis de discurso",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-006",
    modulo: "Neurolengua",
    area: "Semántica",
    areaClinica: "lenguaje",
    subarea: "Semántica",
    franjaEtaria: "7-12",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Comprender y producir lenguaje figurado (metáforas, refranes)",
    definicionOperativa: "El/la paciente identificará el significado no literal de expresiones idiomáticas, metáforas y refranes frecuentes del español, y podrá explicarlos con sus propias palabras.",
    actividadesClinicas: "Presentación de refranes con explicación contextual. Juegos de adivinanza con metáforas. Lectura de textos con lenguaje figurado. Creación propia de metáforas sencillas.",
    actividadesFamilia: "Comentar el significado de refranes cotidianos. Identificar metáforas en canciones o películas. Juego de 'adivina qué quiere decir'.",
    metaPorcentaje: "75% de comprensión en 10 expresiones presentadas",
    intentosSugeridos: "5-6 por sesión",
    recomendacionClinica: "Comenzar con expresiones de alta frecuencia en el contexto cultural del paciente.",
    indicadorTipo: "Comprensión y explicación verbal",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-007",
    modulo: "Neurolengua",
    area: "Léxico",
    areaClinica: "lenguaje",
    subarea: "Categorías semánticas",
    franjaEtaria: "3-6",
    nivelDificultad: "básico",
    nombreObjetivo: "Clasificar objetos en categorías semánticas básicas",
    definicionOperativa: "El/la paciente agrupará objetos en categorías semánticas (animales, alimentos, ropa, muebles, transportes) señalando o nombrando al menos 4 elementos por categoría.",
    actividadesClinicas: "Juegos de clasificación con tarjetas. Identificar el intruso en una categoría. Dominó temático. Asociación de imágenes por categorías.",
    actividadesFamilia: "Juego de 'busca todas las cosas de comer'. Ordenar la compra por categorías. Clasificar juguetes por tipo. Mirar libros temáticos juntos.",
    metaPorcentaje: "4+ ítems por categoría en el 80% de las sesiones",
    intentosSugeridos: "3 categorías por sesión",
    recomendacionClinica: "Comenzar con categorías de alta frecuencia (alimentos, animales). Usar objetos reales antes que imágenes.",
    indicadorTipo: "Clasificación y denominación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "NL-008",
    modulo: "Neurolengua",
    area: "Lenguaje Comprensivo-Expresivo",
    areaClinica: "lenguaje",
    subarea: "Morfología",
    franjaEtaria: "4-8",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Usar correctamente la concordancia de género y número",
    definicionOperativa: "El/la paciente producirá sintagmas nominales con concordancia correcta de género (el/la, un/una) y número (singular/plural) en al menos el 80% de sus producciones.",
    actividadesClinicas: "Corrección implícita de concordancias. Juegos de 'uno y muchos'. Descripciones de láminas corrigiendo errores. Completar oraciones con determinantes.",
    actividadesFamilia: "Señalar diferencias entre uno y varios objetos. Cantar canciones con plurales. Contar objetos enfatizando el plural.",
    metaPorcentaje: "80% de concordancias correctas en muestra de habla",
    intentosSugeridos: "10 ítems por sesión",
    recomendacionClinica: "Usar recasts naturales; no corrección directa. Registrar en muestra de lenguaje espontáneo.",
    indicadorTipo: "Análisis morfológico de muestra",
    estadoBanco: "activo",
  },

  // ─── HABLA ───────────────────────────────────────────────────────────────────
  {
    idObjetivo: "HA-001",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Articulación",
    franjaEtaria: "2-5",
    nivelDificultad: "básico",
    nombreObjetivo: "Producir fonemas oclusivos y nasales en posición inicial de palabra",
    definicionOperativa: "El/la paciente producirá los fonemas /p/, /b/, /t/, /d/, /k/, /g/, /m/, /n/ en posición inicial de sílaba en palabras aisladas y en frases cortas con un 80% de precisión.",
    actividadesClinicas: "Ejercicios de imitación de sílabas. Juego de denominación con palabras que inician con el fonema objetivo. Canciones y rimas. Pares mínimos.",
    actividadesFamilia: "Leer libros con aliteración. Cantar canciones con el sonido objetivo. Nombrar imágenes del fonema trabajado cada día.",
    metaPorcentaje: "80% de producción correcta en palabras aisladas",
    intentosSugeridos: "20 producciones por sesión",
    recomendacionClinica: "No corregir en habla espontánea; reforzar en actividades dirigidas. Verificar audición normal.",
    indicadorTipo: "Producción articulatoria",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-002",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Procesos fonológicos",
    franjaEtaria: "3-6",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Reducir procesos de simplificación fonológica (sustitución y omisión)",
    definicionOperativa: "El/la paciente reducirá los procesos de sustitución y omisión de fonemas en posiciones media y final de palabra, mejorando la estructura silábica CVC y CCVC.",
    actividadesClinicas: "Análisis de errores fonológicos con retroalimentación visual. Mínimos pares con significado. Ejercicios de segmentación silábica. Bombardeo auditivo.",
    actividadesFamilia: "Leer en voz alta lentamente, modelando la palabra correcta. Juego de 'repite cómo yo lo digo'. Escuchar audios de palabras objetivo.",
    metaPorcentaje: "Reducción del 50% en errores respecto al baseline en 8 semanas",
    intentosSugeridos: "15 palabras objetivo por sesión",
    recomendacionClinica: "Priorizar fonemas de adquisición temprana. Usar feedback visual (espejo, app de feedback).",
    indicadorTipo: "Análisis de errores fonológicos",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-003",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Inteligibilidad",
    franjaEtaria: "4-7",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Mejorar la inteligibilidad del habla espontánea",
    definicionOperativa: "El/la paciente aumentará su porcentaje de inteligibilidad en habla espontánea con interlocutores no familiares del 50% al 80% o más.",
    actividadesClinicas: "Juegos de descripción sin apoyo visual para el interlocutor. Grabaciones y análisis de inteligibilidad. Práctica en situaciones comunicativas reales. Técnicas de desaceleración del habla.",
    actividadesFamilia: "No anticipar lo que el niño quiere decir; esperar que se exprese. Pedir aclaraciones de forma natural. Pedir que repita usando estrategias aprendidas.",
    metaPorcentaje: "80% de inteligibilidad con interlocutor no familiar",
    intentosSugeridos: "Muestra de 50 palabras por sesión",
    recomendacionClinica: "Calcular % de inteligibilidad con interlocutor ciego. Considerar examen auditivo periódico.",
    indicadorTipo: "Ratio de inteligibilidad",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-004",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Fluidez",
    franjaEtaria: "6-12",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Reducir disfluencias e implementar técnicas de fluidez",
    definicionOperativa: "El/la paciente aplicará técnicas de control de fluidez (arranque suave, habla fluida, control de velocidad) reduciendo el porcentaje de sílabas disfluentes por debajo del 3% en conversación.",
    actividadesClinicas: "Entrenamiento en respiración abdominal. Técnica de habla fluida y arranque suave. Práctica de habla en diferentes contextos. Desensibilización a disfluencias.",
    actividadesFamilia: "Mantener contacto visual y escuchar sin interrumpir. No terminar las frases del niño. Hablar con ritmo pausado. Reducir preguntas directas en situaciones de alta demanda.",
    metaPorcentaje: "< 3% de sílabas disfluentes en conversación espontánea",
    intentosSugeridos: "Muestras de 300 sílabas por sesión",
    recomendacionClinica: "Involucrar a la familia en el tratamiento. Coordinar con la escuela. Trabajar la actitud hacia la tartamudez.",
    indicadorTipo: "Porcentaje de sílabas disfluentes",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "HA-005",
    modulo: "Neurolengua",
    area: "Habla",
    areaClinica: "habla",
    subarea: "Discriminación auditiva",
    franjaEtaria: "3-6",
    nivelDificultad: "básico",
    nombreObjetivo: "Discriminar auditivamente pares mínimos de fonemas",
    definicionOperativa: "El/la paciente discriminará de forma auditiva pares mínimos que difieran en un único rasgo fonológico (ej. /p/-/b/, /t/-/d/, /s/-/z/) con un 80% de acierto.",
    actividadesClinicas: "Juegos de 'señala cuál escuchas'. Pares mínimos con imágenes. Bombardeo auditivo. Clasificación de palabras por sonido inicial.",
    actividadesFamilia: "Juego de 'adivina qué palabra dije'. Canciones con pares de palabras similares. Leer rimas y señalar palabras que suenan parecido.",
    metaPorcentaje: "80% de discriminaciones correctas",
    intentosSugeridos: "20 pares por sesión",
    recomendacionClinica: "Descartar hipoacusia antes de iniciar. Comenzar con pares de alta frecuencia.",
    indicadorTipo: "Discriminación auditiva con imagen",
    estadoBanco: "activo",
  },

  // ─── PRAGMÁTICA ───────────────────────────────────────────────────────────────
  {
    idObjetivo: "PR-001",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Comunicación no verbal",
    franjaEtaria: "2-5",
    nivelDificultad: "básico",
    nombreObjetivo: "Mantener contacto visual durante el intercambio comunicativo",
    definicionOperativa: "El/la paciente mantendrá contacto visual con su interlocutor durante al menos el 50% del tiempo de conversación o juego compartido.",
    actividadesClinicas: "Juegos cara a cara con objeto de interés. Rutinas con atención conjunta. Juego del espejo. Actividades interactivas que requieran mirar al otro.",
    actividadesFamilia: "Ponerse a la altura del niño al hablarle. Usar juegos de 'míranos'. Esperar el contacto visual antes de dar lo que pide.",
    metaPorcentaje: "50% del tiempo de interacción con mirada social",
    intentosSugeridos: "Observar en 10 minutos de juego libre",
    recomendacionClinica: "No forzar el contacto visual directo; propiciar situaciones naturales. Considerar perfil sensorial.",
    indicadorTipo: "Observación en juego",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-002",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Conversación",
    franjaEtaria: "3-6",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Respetar los turnos conversacionales",
    definicionOperativa: "El/la paciente respetará los turnos en intercambios conversacionales con el/la profesional y con pares, esperando su turno para hablar en al menos el 80% de las oportunidades.",
    actividadesClinicas: "Juegos de turnos con objeto símbolo. Conversaciones estructuradas con señal visual de turno. Role-play de situaciones cotidianas. Juegos de mesa con turno explícito.",
    actividadesFamilia: "Hablar en familia respetando el turno de cada uno. Usar una 'pelota de hablar'. Juegos de mesa que requieran respetar turnos.",
    metaPorcentaje: "80% de turnos respetados en intercambio de 10 minutos",
    intentosSugeridos: "Observar en conversación libre",
    recomendacionClinica: "Usar señales visuales (luz, tarjeta) al inicio del tratamiento. Reducir apoyos gradualmente.",
    indicadorTipo: "Observación en interacción",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-003",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Habilidades conversacionales",
    franjaEtaria: "5-10",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Iniciar y mantener tópicos de conversación de forma apropiada",
    definicionOperativa: "El/la paciente iniciará temas de conversación relevantes y los mantendrá por al menos 4 intercambios, realizando preguntas y comentarios apropiados al contexto.",
    actividadesClinicas: "Scripts conversacionales con temas de interés. Role-play de situaciones sociales. Análisis de conversaciones grabadas. Juego de 'seguir el tema'.",
    actividadesFamilia: "Conversar en familia sobre temas del interés del niño. Modelar cómo añadir información a un tema. Evitar respuestas monosilábicas.",
    metaPorcentaje: "Mantiene tópico 4+ intercambios en el 75% de las situaciones",
    intentosSugeridos: "3 situaciones conversacionales por sesión",
    recomendacionClinica: "Usar temas de alta motivación para el paciente. Trabajar en grupo pequeño cuando sea posible.",
    indicadorTipo: "Análisis de conversación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-004",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Comunicación intencional",
    franjaEtaria: "1-3",
    nivelDificultad: "básico",
    nombreObjetivo: "Usar gestos comunicativos intencionales (señalar, mostrar, dar)",
    definicionOperativa: "El/la paciente usará gestos deícticos y referenciales (señalar con el índice, mostrar objetos, dar objetos) de forma intencional para comunicar deseos y compartir referentes.",
    actividadesClinicas: "Juego con objetos de alta motivación fuera de alcance. Modelado de gesto de señalar. Actividades de atención conjunta. Rutinas de 'dame/toma'.",
    actividadesFamilia: "Modelar el gesto de señalar en rutinas. Esperar el gesto antes de dar el objeto deseado. Leer cuentos señalando imágenes juntos.",
    metaPorcentaje: "Usa 3 gestos comunicativos diferentes en sesión de juego",
    intentosSugeridos: "Observar en 15 minutos de juego",
    recomendacionClinica: "Trabajar en contextos altamente motivantes. Evitar anticipar todas las necesidades del niño.",
    indicadorTipo: "Inventario de gestos comunicativos",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "PR-005",
    modulo: "Neurolengua",
    area: "Pragmática",
    areaClinica: "pragmática",
    subarea: "Adaptación discursiva",
    franjaEtaria: "6-12",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Adaptar el registro comunicativo al interlocutor y contexto",
    definicionOperativa: "El/la paciente ajustará su lenguaje (vocabulario, tono, formalidad) según las características del interlocutor (adulto/niño, conocido/desconocido) y el contexto (formal/informal).",
    actividadesClinicas: "Role-play con diferentes interlocutores. Análisis de situaciones comunicativas. Comparar formas de hablar en distintos contextos. Grabación y autoevaluación.",
    actividadesFamilia: "Modelar diferencias de registro en la vida diaria. Señalar cómo hablan los personajes en películas según con quién hablan.",
    metaPorcentaje: "Ajuste apropiado en 3 de 4 situaciones de role-play",
    intentosSugeridos: "4 situaciones contrastadas por sesión",
    recomendacionClinica: "Trabajar con situaciones reales del entorno del paciente. Reforzar autoevaluación.",
    indicadorTipo: "Role-play y autoevaluación",
    estadoBanco: "activo",
  },

  // ─── MOTRICIDAD OROFACIAL ─────────────────────────────────────────────────────
  {
    idObjetivo: "MO-001",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Tono muscular",
    franjaEtaria: "2-6",
    nivelDificultad: "básico",
    nombreObjetivo: "Mejorar el tono muscular labial y lingual",
    definicionOperativa: "El/la paciente incrementará el tono y la fuerza muscular de labios y lengua mediante ejercicios de resistencia y estimulación, observando mejora en la postura de reposo y en la articulación.",
    actividadesClinicas: "Masajes de estimulación labial y lingual. Ejercicios de soplo y succión con resistencia. Vibración táctil. Comer alimentos de diferentes texturas. Ejercicios con espátula.",
    actividadesFamilia: "Masajes faciales suaves en rutinas de higiene. Ofrecer alimentos de distintas texturas. Ejercicios de soplo lúdico (velas, molinillos).",
    metaPorcentaje: "Tono adecuado en reposo observado por el profesional en 3 sesiones consecutivas",
    intentosSugeridos: "10 repeticiones de cada ejercicio",
    recomendacionClinica: "Evitar ejercicios sin función comunicativa. Integrar con objetivos articulatorios.",
    indicadorTipo: "Evaluación clínica de tono",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "MO-002",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Praxis",
    franjaEtaria: "2-5",
    nivelDificultad: "básico",
    nombreObjetivo: "Realizar praxis orofaciales básicas bajo consigna verbal e imitación",
    definicionOperativa: "El/la paciente ejecutará al menos 6 praxis orofaciales básicas (abrir boca, sacar lengua, labios juntos, sonrisa, fruncir labios, soplar) ante consigna verbal y/o modelado.",
    actividadesClinicas: "Imitación frente al espejo. Juego de 'caras y gestos'. Uso de soplo lúdico. Modelado de praxis en secuencia. Fotos de referencia para praxis.",
    actividadesFamilia: "Juego del espejo en casa. Soplar velas o molinetes. Imitar caras de animales o personajes. Juegos de soplo con burbujas.",
    metaPorcentaje: "6 de 8 praxis correctas en 3 sesiones consecutivas",
    intentosSugeridos: "5 repeticiones de cada praxis",
    recomendacionClinica: "Comenzar con imitación visual antes de consigna verbal. Incluir praxis en contextos lúdicos.",
    indicadorTipo: "Evaluación de praxis imitativa",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "MO-003",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Respiración",
    franjaEtaria: "3-7",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Establecer patrón respiratorio nasal-oral coordinado con el habla",
    definicionOperativa: "El/la paciente adoptará un patrón respiratorio adecuado al habla: inspiración nasal, espiración oral controlada, con pausas apropiadas en el discurso.",
    actividadesClinicas: "Conciencia de la respiración. Ejercicios de soplo controlado. Habla con control respiratorio en frases cortas, luego largas. Coordinación fonorrespiratoria.",
    actividadesFamilia: "Ejercicios de respiración antes de dormir. Contar hasta 10 en una sola espiración. Actividades de relajación con respiración guiada.",
    metaPorcentaje: "Coordinación fonorrespiratoria apropiada en habla conversacional",
    intentosSugeridos: "5 minutos de ejercicios respiratorios por sesión",
    recomendacionClinica: "Descartar obstrucción nasal. Coordinación con pediatra si hay respiración oral crónica.",
    indicadorTipo: "Observación clínica de patrón respiratorio",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "MO-004",
    modulo: "Neurolengua",
    area: "Motricidad Orofacial",
    areaClinica: "motricidad orofacial",
    subarea: "Deglución",
    franjaEtaria: "5-12",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Corregir el patrón de deglución atípica",
    definicionOperativa: "El/la paciente adoptará un patrón de deglución con lengua en posición correcta (contra el paladar duro anterior) sin interposición lingual, con labios sellados.",
    actividadesClinicas: "Ejercicios de posicionamiento lingual. Biofeedback visual. Deglución con diferentes consistencias. Ejercicios de tonificación lingual. Control en actividades de alimentación.",
    actividadesFamilia: "Recordar la posición de la lengua durante las comidas. Ejercicios de posición de reposo. Control visual frente al espejo durante la comida.",
    metaPorcentaje: "Patrón correcto en el 80% de degluciones observadas",
    intentosSugeridos: "20 degluciones por sesión",
    recomendacionClinica: "Coordinar con ortodoncista si hay maloclusión asociada. Trabajo a largo plazo (6+ meses).",
    indicadorTipo: "Evaluación de deglución observada",
    estadoBanco: "activo",
  },

  // ─── LECTOESCRITURA ───────────────────────────────────────────────────────────
  {
    idObjetivo: "LE-001",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Conciencia fonológica",
    franjaEtaria: "4-6",
    nivelDificultad: "básico",
    nombreObjetivo: "Desarrollar conciencia fonológica: silábica y fonémica",
    definicionOperativa: "El/la paciente segmentará palabras en sílabas, identificará rimas, reconocerá el fonema inicial y final de palabras, y realizará síntesis silábica con un 80% de acierto.",
    actividadesClinicas: "Aplaudir sílabas. Juegos de rimas. Identificar el sonido inicial. Síntesis fonémica con fichas. Juego del 'veo veo' con sonidos.",
    actividadesFamilia: "Cantar canciones con rimas. Aplaudir las sílabas de nombres de familia. Jugar a 'busca palabras que empiecen con…'.",
    metaPorcentaje: "80% de éxito en 4 tareas fonológicas básicas",
    intentosSugeridos: "10 ítems por tarea y sesión",
    recomendacionClinica: "Seguir la secuencia: rima → sílaba → fonema. Usar material auditivo y visual simultáneamente.",
    indicadorTipo: "Prueba de conciencia fonológica",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "LE-002",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Decodificación",
    franjaEtaria: "5-7",
    nivelDificultad: "básico",
    nombreObjetivo: "Reconocer y leer palabras monosílabas y bisílabas",
    definicionOperativa: "El/la paciente leerá palabras monosílabas y bisílabas de vocabulario frecuente con decodificación fonológica correcta en al menos el 80% de los intentos.",
    actividadesClinicas: "Lectura de carteles con sílabas directas. Juego de dominó de sílabas. Lotería de palabras. Asociación palabra-imagen.",
    actividadesFamilia: "Leer etiquetas de alimentos. Juego de buscar palabras conocidas en un texto. Cartas y tarjetas con palabras cortas.",
    metaPorcentaje: "80% de palabras leídas correctamente en listado de 20",
    intentosSugeridos: "20 palabras por sesión",
    recomendacionClinica: "Comenzar con sílabas directas (CV). Descartar déficit visual. Coordinar con maestra.",
    indicadorTipo: "Listado de palabras",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "LE-003",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Comprensión lectora",
    franjaEtaria: "6-9",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Comprender textos breves respondiendo preguntas literales e inferenciales",
    definicionOperativa: "El/la paciente leerá textos de 3-5 oraciones y responderá correctamente al menos el 80% de preguntas literales e inferenciales simples sobre lo leído.",
    actividadesClinicas: "Lectura con preguntas guiadas. Ordenar oraciones de un texto. Identificar idea principal y detalles. Completar mapa de historia.",
    actividadesFamilia: "Leer juntos un párrafo y preguntar '¿qué pasó?' y '¿por qué crees que…?'. Releer el mismo texto varias veces.",
    metaPorcentaje: "80% de respuestas correctas a preguntas del texto",
    intentosSugeridos: "1-2 textos por sesión",
    recomendacionClinica: "Comenzar con textos de estructura narrativa. Aumentar dificultad gradualmente.",
    indicadorTipo: "Cuestionario de comprensión",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "LE-004",
    modulo: "Neurolengua",
    area: "Lectoescritura",
    areaClinica: "lectoescritura",
    subarea: "Escritura",
    franjaEtaria: "7-12",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Producir textos escritos con cohesión y coherencia básica",
    definicionOperativa: "El/la paciente producirá textos escritos de al menos 5 oraciones con tema central identificable, uso de conectores y ortografía consistente con su nivel escolar.",
    actividadesClinicas: "Planificación de texto con mapa conceptual. Escritura guiada con modelo. Revisión y reescritura. Producción de texto a partir de imágenes.",
    actividadesFamilia: "Escribir listas de compras. Redactar notas para familiares. Llevar un diario simple. Escribir tarjetas de cumpleaños.",
    metaPorcentaje: "Texto de 5+ oraciones con coherencia evaluada como adecuada",
    intentosSugeridos: "1 texto por sesión con revisión",
    recomendacionClinica: "Separar evaluación de contenido de la ortografía. Usar procesador de texto para facilitar revisión.",
    indicadorTipo: "Rúbrica de escritura",
    estadoBanco: "activo",
  },

  // ─── COGNICIÓN ────────────────────────────────────────────────────────────────
  {
    idObjetivo: "CO-001",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Atención",
    franjaEtaria: "3-7",
    nivelDificultad: "básico",
    nombreObjetivo: "Mantener la atención sostenida en tarea estructurada por 10 minutos",
    definicionOperativa: "El/la paciente permanecerá en tarea durante al menos 10 minutos continuos en actividades estructuradas (puzzle, láminas, tareas de papel), con mínimas redirecciones.",
    actividadesClinicas: "Actividades de mesa con materiales motivantes. Temporizador visual. Registro de tiempo en tarea. Actividades de atención selectiva y dividida.",
    actividadesFamilia: "Actividades de mesa de 10 minutos diarios. Uso de timer visual. Evitar estímulos distractores durante las tareas. Refuerzo positivo al completar.",
    metaPorcentaje: "10 minutos continuos en tarea en 4 de 5 sesiones",
    intentosSugeridos: "2-3 tareas por sesión",
    recomendacionClinica: "Comenzar con actividades de alta motivación. Reducir distractores ambientales. Documentar tiempo en tarea.",
    indicadorTipo: "Tiempo en tarea",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-002",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Memoria",
    franjaEtaria: "5-10",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Mejorar la memoria de trabajo verbal (retención de información auditiva)",
    definicionOperativa: "El/la paciente repetirá correctamente secuencias de palabras y dígitos de longitud creciente (hasta 5 elementos), y recordará información verbal escuchada en contexto.",
    actividadesClinicas: "Repetición de dígitos y palabras. Juego de 'memoria secuencial'. Recuerdo diferido de palabras. Seguir instrucciones de varios pasos.",
    actividadesFamilia: "Juego de 'Veo, veo, recuerdo'. Leer una lista y pedir que la repita. Juego de memoria con tarjetas. Recordar lo comido en el almuerzo.",
    metaPorcentaje: "Repite 5 dígitos en orden directo en 3 de 4 intentos",
    intentosSugeridos: "10 ítems por sesión",
    recomendacionClinica: "Evaluar memoria con prueba estandarizada de base. Coordinar con neuropsicólogo.",
    indicadorTipo: "Span de dígitos y palabras",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-003",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Funciones ejecutivas",
    franjaEtaria: "6-12",
    nivelDificultad: "intermedio",
    nombreObjetivo: "Mejorar la planificación y organización en tareas cotidianas",
    definicionOperativa: "El/la paciente secuenciará pasos para completar una tarea de múltiples etapas, anticipará materiales necesarios y seguirá el plan con supervisión mínima.",
    actividadesClinicas: "Organización de mochila escolar. Planificación de actividades con pasos escritos. Uso de agenda y checklist. Secuenciación de tareas con tarjetas.",
    actividadesFamilia: "Usar agenda o tablero de tareas diarias. Pedir al niño que planifique su rutina matutina. Preparar juntos lo necesario para el día siguiente.",
    metaPorcentaje: "Completa tarea de 5 pasos con 1 o menos redirecciones en 3 sesiones",
    intentosSugeridos: "2 tareas de planificación por sesión",
    recomendacionClinica: "Usar apoyos visuales (checklists, secuencias de imágenes). Graduar la complejidad.",
    indicadorTipo: "Observación de planificación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-004",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Inhibición",
    franjaEtaria: "6-12",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Desarrollar control inhibitorio ante respuestas impulsivas",
    definicionOperativa: "El/la paciente aplicará estrategias de pausa-reflexión (stop-think-act) antes de responder en situaciones de alta demanda cognitiva y social, reduciendo respuestas impulsivas.",
    actividadesClinicas: "Juego de 'Simón dice'. Stroop adaptado. Tareas go/no-go. Entrenamiento en autoinstrucciones. Registro de impulsos y pausas.",
    actividadesFamilia: "Enseñar la señal de 'pausa' antes de actuar. Reforzar cuando el niño se detiene a pensar. Juegos de mesa que requieran esperar.",
    metaPorcentaje: "70% de respuestas reflexivas en situaciones identificadas",
    intentosSugeridos: "5 situaciones de práctica por sesión",
    recomendacionClinica: "Coordinar con psicólogo. Trabajar autoinstrucciones verbales. Considerar TDA si persiste.",
    indicadorTipo: "Tasa de respuestas impulsivas/reflexivas",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "CO-005",
    modulo: "Neurolengua",
    area: "Cognición",
    areaClinica: "cognición",
    subarea: "Flexibilidad cognitiva",
    franjaEtaria: "7-12",
    nivelDificultad: "avanzado",
    nombreObjetivo: "Mejorar la flexibilidad cognitiva ante cambios de tarea y reglas",
    definicionOperativa: "El/la paciente realizará transiciones entre tareas o cambios de regla sin resistencia excesiva, ajustando su conducta en menos de 2 minutos en el 75% de las situaciones.",
    actividadesClinicas: "Juegos con cambio de reglas. Clasificación de objetos con criterio cambiante. Actividades de role switching. Situaciones de resolución de problemas con cambios.",
    actividadesFamilia: "Anticipar los cambios de actividad con aviso previo. Practicar cambios en juegos en casa. Reforzar la adaptación al cambio con elogio específico.",
    metaPorcentaje: "75% de transiciones sin resistencia en 2 minutos",
    intentosSugeridos: "3-4 situaciones de cambio por sesión",
    recomendacionClinica: "Anticipar los cambios verbalmente. Trabajar en contextos de baja ansiedad primero. Coordinar con equipo escolar.",
    indicadorTipo: "Tiempo y calidad de transición",
    estadoBanco: "activo",
  },

  // ─── ESTIMULACIÓN TEMPRANA ────────────────────────────────────────────────────
  {
    idObjetivo: "ET-001",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Desarrollo sensorial",
    franjaEtaria: "0-2",
    nivelDificultad: "básico",
    nombreObjetivo: "Seguimiento visual de objetos en movimiento",
    definicionOperativa: "El/la bebé rastreará visualmente un objeto en movimiento en planos horizontal, vertical y circular, manteniendo la mirada por al menos 3 segundos.",
    actividadesClinicas: "Seguimiento de objeto contrastado a 30 cm. Uso de luz linterna en cuarto oscuro. Móvil a nivel de ojos. Seguimiento de rostro del adulto.",
    actividadesFamilia: "Mover objetos de colores brillantes frente al bebé. Hablarle mientras se mueve lentamente frente a él. Usar móvil colgado en la cuna.",
    metaPorcentaje: "Seguimiento en 3 planos por 3+ segundos en 3 sesiones",
    intentosSugeridos: "5 ensayos por plano",
    recomendacionClinica: "Evaluar agudeza visual si hay sospecha. Usar colores contrastados (negro/blanco/rojo). Verificar posición óptima.",
    indicadorTipo: "Observación de seguimiento",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-002",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Imitación",
    franjaEtaria: "0-2",
    nivelDificultad: "básico",
    nombreObjetivo: "Imitar gestos y vocalizaciones del adulto",
    definicionOperativa: "El/la bebé imitará al menos 3 gestos faciales simples (abrir boca, sacar lengua, sonreír) y 3 vocalizaciones (/a/, /m/, /b/) en respuesta al modelado del adulto.",
    actividadesClinicas: "Juego de imitación cara a cara. Modelado de vocalizaciones en turno. Juego de espejo. Imitación de sonidos ambientales simples.",
    actividadesFamilia: "Jugar a imitar gestos frente al espejo. Imitar las vocalizaciones del bebé y esperar respuesta. Turno de vocalización durante cambio de pañal o baño.",
    metaPorcentaje: "Imita 3 gestos y 3 vocalizaciones en sesión observada",
    intentosSugeridos: "10 oportunidades por sesión",
    recomendacionClinica: "Esperar la respuesta espontánea del bebé. Imitar también al bebé para fortalecer el intercambio recíproco.",
    indicadorTipo: "Observación de imitación",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-003",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Comprensión temprana",
    franjaEtaria: "1-2",
    nivelDificultad: "básico",
    nombreObjetivo: "Comprender palabras funcionales del entorno familiar",
    definicionOperativa: "El/la niño/a comprenderá al menos 20 palabras de su entorno cotidiano (nombres de personas, objetos del hogar, acciones básicas) respondiendo con acción, señal o mirada.",
    actividadesClinicas: "Rutinas de denominación en juego. Juego de 'busca el…'. Señalar imágenes en cuentos. Seguir instrucciones de 1 paso con vocabulario familiar.",
    actividadesFamilia: "Nombrar objetos constantemente en las rutinas. Pedir '¿dónde está el…?' señalando con entusiasmo. Leer cuentos de imágenes simples nombrando y preguntando.",
    metaPorcentaje: "Comprensión de 20+ palabras registradas en inventario",
    intentosSugeridos: "Registro de inventario MacArthur mensual",
    recomendacionClinica: "Usar inventario de comunicación del desarrollo (CDI). Descartar hipoacusia si hay retraso.",
    indicadorTipo: "Inventario de vocabulario comprensivo",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-004",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Primeras palabras",
    franjaEtaria: "1-3",
    nivelDificultad: "básico",
    nombreObjetivo: "Producir primeras palabras funcionales con intención comunicativa",
    definicionOperativa: "El/la niño/a producirá al menos 10 palabras o aproximaciones reconocibles de forma espontánea e intencional para comunicar deseos, necesidades o nombrar objetos presentes.",
    actividadesClinicas: "Modelado de palabras en contextos de alta motivación. Sabotaje del entorno para elicitar comunicación. Juego de 'pedir con palabras'. Expansión de vocalizaciones.",
    actividadesFamilia: "Esperar la demanda verbal antes de dar el objeto. Modelar la palabra correcta sin corregir. Crear situaciones donde el niño necesite pedir (objeto favorito visible pero fuera de alcance).",
    metaPorcentaje: "10+ palabras o aproximaciones en inventario expresivo",
    intentosSugeridos: "Registro semanal en inventario",
    recomendacionClinica: "Considerar SAC si no hay palabras a los 18 meses. Derivar a evaluación audiológica si hay dudas.",
    indicadorTipo: "Inventario expresivo de vocabulario",
    estadoBanco: "activo",
  },
  {
    idObjetivo: "ET-005",
    modulo: "Neurolengua",
    area: "Estimulación Temprana",
    areaClinica: "estimulación temprana",
    subarea: "Juego",
    franjaEtaria: "1-3",
    nivelDificultad: "básico",
    nombreObjetivo: "Desarrollar juego funcional y simbólico básico",
    definicionOperativa: "El/la niño/a participará en juego funcional con objetos (uso convencional) y comenzará a demostrar juego simbólico básico (hacer 'como si', dar de comer a muñeca, hablar por teléfono de juguete).",
    actividadesClinicas: "Modelado de juego funcional con objetos. Juego paralelo con profesional. Introducción de juego simbólico con secuencias de 1-2 pasos. Juego de roles simples.",
    actividadesFamilia: "Jugar juntos con objetos del hogar usándolos de forma convencional. Modelar juego simbólico (ej. dar de comer a un peluche). Jugar a las cocinitas o mecánicos.",
    metaPorcentaje: "5+ episodios de juego funcional y 2+ de juego simbólico por sesión",
    intentosSugeridos: "20 minutos de juego libre observado",
    recomendacionClinica: "El nivel de juego es predictor del desarrollo del lenguaje. Documentar tipo y complejidad del juego.",
    indicadorTipo: "Escala de niveles de juego",
    estadoBanco: "activo",
  },
];

async function seedGoalLibrary() {
  console.log("Limpiando banco de objetivos anterior...");
  await db.delete(goalLibraryTable);
  const inserted = await db.insert(goalLibraryTable).values(goals.map(g => ({
    idObjetivo: g.idObjetivo,
    nombreObjetivo: g.nombreObjetivo,
    modulo: g.modulo,
    area: g.area,
    areaClinica: g.areaClinica,
    subarea: g.subarea,
    franjaEtaria: g.franjaEtaria,
    nivelDificultad: g.nivelDificultad,
    estadoBanco: g.estadoBanco,
    definicionOperativa: g.definicionOperativa ?? null,
    actividadesClinicas: g.actividadesClinicas ?? null,
    actividadesFamilia: g.actividadesFamilia ?? null,
    metaPorcentaje: g.metaPorcentaje ?? null,
    indicadorTipo: g.indicadorTipo ?? null,
    intentosSugeridos: g.intentosSugeridos ?? null,
    recomendacionClinica: g.recomendacionClinica ?? null,
  }))).returning();
  console.log(`✅ ${inserted.length} objetivos clínicos cargados en el banco`);
}

seedGoalLibrary().catch(console.error).finally(() => process.exit(0));
